### ISSUE TITLE
how to use promise on setTimeout via songbird?

### ISSUE THREAD

**Issue by vanessachem** [duereg/songbird#4]
i tried the mixin pattern as documented

setTimeout.promise(1000).then()

but i was having 

TypeError: number is not a function
    at Timer.listOnTimeout (timers.js:89:15)

**Comment by duereg** [comment]
It's not possible. 

I haven't documented this, I'll add the appropriate information to the README. 

The reason is:

The function should conform to node.js convention of accepting a callback as last argument and calling that callback with error as the first argument and success value on the second argument.

Since setTimeout doesn't adhere to this, you can't do it. You could wrap setTimeout in another function, but I think at that point you'd be better served simply creating a promise yourself and having setTimeout call resolve(), if you really need a promise
